apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-push-image
  namespace: ci-cd
spec:
  params:
    - name: IMAGE
      type: string
    - name: DOCKERFILE
      type: string
      default: "./Dockerfile"
    - name: CONTEXT
      type: string
      default: "."
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      workingDir: $(workspaces.source.path)
      args:
        - --dockerfile=$(params.DOCKERFILE)
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(params.IMAGE)
        - --insecure
        - --skip-tls-verify
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
  volumes:
    - name: docker-config
      secret:
        secretName: harbor-dc-creds
        items:
          - key: .dockerconfigjson
            path: config.json
